# Generated by Django 2.2.16 on 2022-07-22 20:15

from django.db import migrations, models
import users.validations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[users.validations.validate_username]),
        ),
    ]
